### PR TITLE
Updated CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by CoderUsman**

### CODE REVIEW

**Review by melvincwng — APPROVED** [review]
LGTM!

**Comment by melvincwng** [comment]
@CoderUsman Hey there, thanks for your contribution 🙏

Don't forget to follow me on GitHub for updates to this open source project! I have also sent you an invite to join this organization 😊

Take care!

**Comment by CoderUsman** [comment]
@melvincwng Hi!

Of course I'm gonna follow you, and I have accepted the invitation, thanks 😊!

Take care, and bye!

**Comment by melvincwng** [comment]
@CoderUsman Cheers mate, welcome to the team! 👏

**Comment by CoderUsman** [comment]
@melvincwng Thanks man 😃😄!

**Pull request merged**
